### ISSUE TITLE
fpm模式下session setcookie报错

### ISSUE THREAD

**Issue by AFKL1919** [Yurunsoft/imi#141]
# 环境
windows10 PHP 7.4.3 (cli) (built: Feb 18 2020 17:29:57) ( NTS Visual C++ 2017 x64 )

# 复现
控制器如下：
```php
<?php

namespace ImiApp\ApiServer\Controller;

use Imi\App;
use Imi\Db\Db;
use Imi\Redis\Redis;
use Imi\Server\Http\Controller\HttpController;
use Imi\Server\Http\Route\Annotation\Action;
use Imi\Server\Http\Route\Annotation\Controller;
use Imi\Server\Http\Route\Annotation\Route;
use Imi\Server\View\Annotation\HtmlView;
use Imi\Server\View\Annotation\View;
use Imi\Server\Session\Session;

/**
 * @Controller("/")
 * @HtmlView(baseDir="index/")
 */
class IndexController extends HttpController
{
   // composer create-project imiphp/project-http 命令产生的默认代码

    /**
     * @Action
     * @View(renderType="html")
     * @HtmlView(template="session")
     * @return array
     */
    public function session()
    {
        $data = $this->request->get("value", "null");
        Session::set("value", $data);
        Session::save();

        if ($this->request->get("show", false)) {
            return ["session" => Session::get("value", "null")];
        } else {
            return ["session" => "set:".$data];
        }
    }
}
```

config如下：
```php
<?php

use Imi\Log\LogLevel;
return [
    'configs'    =>    [
    ],
    // bean扫描目录
    'beanScan'    =>    [
        'ImiApp\ApiServer\Controller',
    ],
    'beans'    =>    [
        'SessionManager'    =>    [
            'handlerClass'    =>    \Imi\Server\Session\Handler\File::class,
        ],
        'SessionFile'    =>    [
            'savePath'    =>    dirname(__DIR__, 2) . '/.runtime/.session/',
        ],
        'SessionConfig'    =>    [
            'name'    =>    'PHPSESSION',
        ],
        'SessionCookie'    =>    [
            'enable'    =>  true,
            'lifetime'    =>    86400 * 30,
            'httponly' => true,
        ],
        'HttpDispatcher'    =>    [
            'middlewares'    =>    [
                \ImiApp\ApiServer\Middleware\PoweredBy::class,
                \Imi\Server\Session\Middleware\HttpSessionMiddleware::class,
                \Imi\Server\Http\Middleware\RouteMiddleware::class,
            ],
        ],
        'HtmlView'    =>    [
            'templatePath'    =>    dirname(__DIR__) . '/template/',
            // 支持的模版文件扩展名，优先级按先后顺序
            'fileSuffixs'        =>    [
                'tpl',
                'html',
                'php'
            ],
        ]
    ],
];
```

直接命令行  `php.exe ./vendor/imiphp/imi/src/Cli/bin/imi-cli fpm/start` 启动

清空所有session和客户端的cookie后，尝试访问`session`路由时出现命令行以下报错：
```
Fri Sep  3 15:27:34 2021] 127.0.0.1:26313 [200]: GET /session - Uncaught TypeError: setcookie() expects parameter 1 to be string, null given in [hide]\vendor\imiphp\imi-fpm\src\Http\Message\FpmResponse.php:89
Stack trace:
#0 [hide]\vendor\imiphp\imi-fpm\src\Http\Message\FpmResponse.php(89): setcookie(NULL, NULL, 0, '/', '', false, false)#1 [hide]\vendor\imiphp\imi-fpm\src\Http\Message\FpmResponse.php(101): Imi\Fpm\Http\Message\FpmResponse->sendHeaders()
#2 [hide]\vendor\imiphp\imi\src\Server\Http\Error\JsonErrorHandler.php(56): Imi\Fpm\Http\Message\FpmResponse->send() 
#3 [hide]\vendor\imiphp\imi\src\Server\Http\Error\ErrorHandler.php(19): Imi\Server\Http\Error\JsonErrorHandler->handle(Object(TypeError))
#4 [hide]\vendor\imiphp\imi-fpm\src\Server\Server.php(96): Imi\Server\Http\Error\ErrorHandler->handle(Object(TypeError))
#5 [hide] in [hide]\vendor\imiphp\imi-fpm\src\Http\Message\FpmResponse.php on line 89
```
.runtime的session文件是正常写入的，但服务器为客户端设置cookie失败。

# 预期
在用户session为空的情况下，服务器自动为客户端设置cookie

**Comment by AFKL1919** [comment]
也有可能是我的配置有问题（
如果是我的问题请帮我指出来（👻

**Comment by Yurunsoft** [comment]
问题已经修复，尝试把`imiphp/imi-fpm`更新到`2.0.x-dev`再试一下

**Comment by AFKL1919** [comment]
解决了，Thanks👍
