### ISSUE TITLE
Db::query()->joinRaw()强类型报错

### ISSUE THREAD

**Issue by Mjc960512** [Yurunsoft/imi#192]
原代码
```php
$model = Db::query()->table('vehicle', 'a')->joinRaw('left join train_number b ON a.vehicle_id=b.vehicle_id and b.departure_date=' . strtotime($departure_time))
            ->fieldRaw('a.vehicle_id,a.car_number,a.car_type,a.car_model,a.seat,a.head_image,b.train_number_id,b.surplus_seat,b.is_completed,b.waiting_time,b.agree_or_not,b.general_user_id,b.routes,b.remarks,b.departure_time');
```

报错信息
```php
[2021-10-29 14:36:24] imi.ERROR: TypeError: Typed property Imi\Db\Query\Join::$left must be string, null used in /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Db/Query/Join.php:57
Stack trace:
#0 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Db/Query/Query.php(511): Imi\Db\Query\Join->__construct()
#1 /mnt/c/www/yuanzhi-back-end/ApiServer/Module/General/Service/Schedule/GTrainNumberService.php(38): Imi\Db\Query\Query->joinRaw()
#2 /mnt/c/www/yuanzhi-back-end/ApiServer/Module/General/Controller/Vehicle.php(172): ImiApp\ApiServer\Module\General\Service\Schedule\GTrainNumberService->queryVehicle()
#3 /run/shm/imi-27142-112.php(79): ImiApp\ApiServer\Module\General\Controller\Vehicle->queryVehicle()
#4 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Bean/BeanProxy.php(244): Vehicle__Bean__112->{closure}()
#5 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Bean/BeanProxy.php(42): Imi\Bean\BeanProxy::callOrigin()
#6 /run/shm/imi-27142-112.php(81): Imi\Bean\BeanProxy::call()
#7 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Http/Middleware/ActionMiddleware.php(66): Vehicle__Bean__112->queryVehicle()
#8 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Http/Middleware/ActionWrapMiddleware.php(50): Imi\Server\Http\Middleware\ActionMiddleware->process()
#9 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Http/RequestHandler.php(48): Imi\Server\Http\Middleware\ActionWrapMiddleware->process()
#10 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Http/Middleware/OptionsMiddleware.php(100): Imi\Server\Http\RequestHandler->handle()
#11 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Http/RequestHandler.php(48): Imi\Server\Http\Middleware\OptionsMiddleware->process()
#12 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Http/Middleware/RouteMiddleware.php(51): Imi\Server\Http\RequestHandler->handle()
#13 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Http/RequestHandler.php(48): Imi\Server\Http\Middleware\RouteMiddleware->process()
#14 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Session/Middleware/HttpSessionMiddleware.php(52): Imi\Server\Http\RequestHandler->handle()
#15 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Http/RequestHandler.php(48): Imi\Server\Session\Middleware\HttpSessionMiddleware->process()
#16 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Http/Dispatcher.php(36): Imi\Server\Http\RequestHandler->handle()
#17 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi-swoole/src/Server/Http/Listener/BeforeRequest.php(49): Imi\Server\Http\Dispatcher->dispatch()
#18 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Event/TEvent.php(195): Imi\Swoole\Server\Http\Listener\BeforeRequest->handle()
#19 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi-swoole/src/Server/Http/Server.php(130): Imi\Server\Contract\BaseServer->trigger()
#20 {main}  
```

**Comment by Mjc960512** [comment]
Complaint::query()->table('complaint', 'a')
            ->joinRaw('LEFT JOIN member_auth b ON a.member_id=b.member_id AND b.identity_type=3')->field('a.*');

模型调用也会报

**Comment by Yurunsoft** [comment]
已修复
