### ISSUE TITLE
权限bug，强类型

### ISSUE THREAD

**Issue by Mjc960512** [Yurunsoft/imi#195]
调用代码
```
<?php
use Imi\AC\AccessControl\Role;
Role::create($data['name'], $data['code'], isset($data['description']) ? $data['description'] : '')
```

错误
```log
[2021-10-29 16:37:14] imi.ERROR: TypeError: Argument 1 passed to Imi\AC\Service\RoleService::get() must be of the type int, string given, called in /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi-access-control/src/AccessControl/Role.php on line 58 and defined in /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi-access-control/src/Service/RoleService.php:48
Stack trace:
#0 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi-access-control/src/AccessControl/Role.php(58): Imi\AC\Service\RoleService->get()
#1 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi-access-control/src/AccessControl/Role.php(106): Imi\AC\AccessControl\Role->__construct()
#2 /mnt/c/www/yuanzhi-back-end/ApiServer/Module/General/Service/GeneralUser/GRoleService.php(36): Imi\AC\AccessControl\Role::create()
#3 /mnt/c/www/yuanzhi-back-end/ApiServer/Module/General/Controller/GeneralUser/Role.php(50): ImiApp\ApiServer\Module\General\Service\GeneralUser\GRoleService->addRole()
#4 /run/shm/imi-13916-70.php(25): ImiApp\ApiServer\Module\General\Controller\GeneralUser\Role->addRole()
#5 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Bean/BeanProxy.php(244): Role__Bean__70->{closure}()
#6 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Bean/BeanProxy.php(57): Imi\Bean\BeanProxy::callOrigin()
#7 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Aop/AroundJoinPoint.php(33): Imi\Bean\BeanProxy::Imi\Bean\{closure}()
#8 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Db/Aop/TransactionAop.php(75): Imi\Aop\AroundJoinPoint->proceed()
#9 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Util/DelayClassCallable.php(41): Imi\Db\Aop\TransactionAop->parseTransaction()
#10 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Bean/BeanProxy.php(70): Imi\Util\DelayClassCallable->__invoke()
#11 /run/shm/imi-13916-70.php(27): Imi\Bean\BeanProxy::call()
#12 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Http/Middleware/ActionMiddleware.php(66): Role__Bean__70->addRole()
#13 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Http/Middleware/ActionWrapMiddleware.php(50): Imi\Server\Http\Middleware\ActionMiddleware->process()
#14 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Http/RequestHandler.php(48): Imi\Server\Http\Middleware\ActionWrapMiddleware->process()
#15 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Http/Middleware/OptionsMiddleware.php(100): Imi\Server\Http\RequestHandler->handle()
#16 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Http/RequestHandler.php(48): Imi\Server\Http\Middleware\OptionsMiddleware->process()
#17 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Http/Middleware/RouteMiddleware.php(51): Imi\Server\Http\RequestHandler->handle()
#18 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Http/RequestHandler.php(48): Imi\Server\Http\Middleware\RouteMiddleware->process()
#19 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Session/Middleware/HttpSessionMiddleware.php(52): Imi\Server\Http\RequestHandler->handle()
#20 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Http/RequestHandler.php(48): Imi\Server\Session\Middleware\HttpSessionMiddleware->process()
#21 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Server/Http/Dispatcher.php(36): Imi\Server\Http\RequestHandler->handle()
#22 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi-swoole/src/Server/Http/Listener/BeforeRequest.php(49): Imi\Server\Http\Dispatcher->dispatch()
#23 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi/src/Event/TEvent.php(195): Imi\Swoole\Server\Http\Listener\BeforeRequest->handle()
#24 /mnt/c/www/yuanzhi-back-end/vendor/imiphp/imi-swoole/src/Server/Http/Server.php(130): Imi\Server\Contract\BaseServer->trigger()
#25 {main}  
```

**Comment by Yurunsoft** [comment]
![II% 1VQV(W69S`@I3QN6O)F](https://user-images.githubusercontent.com/20104656/139410244-da07fe15-2982-43f3-91b6-f217dea28d3e.png)

代码不会像报错信息里调用堆栈这么走，尝试更新最新版本
