### ISSUE TITLE
Swoole 子服务器（单项目多端口多协议） 不成功

### ISSUE THREAD

**Issue by ayhome** [Yurunsoft/imi#272]
* 将tcp 作为主服务器, websocket 作为子服务失败,  以下是本机环境

```
imiphp/imi                         v2.1.0   imi 是一款支持长连接微服务分布式的 PHP 开发�...    
imiphp/imi-macro                   v2.1.0   支持在 imi 框架中使用宏定义   
imiphp/imi-swoole                  v2.1.1   imi swoole component   
imiphp/imi-workerman               v2.1.0   imi workerman component   

```

### 实现步骤  

1. 创建 TCP Server 项目：composer create-project imiphp/project-tcp:~2.1.0   
2. 再 创建 WebSocket Server 项目：composer create-project imiphp/project-websocket:~2.1.0  
3. 将 WebSocket 目录 复制到  步骤1 的根目录下  
4. 配置文件
```  
// 子服务器（端口监听）配置
  'subServers'      => [
    'WebSocketServer'   =>  [
        'namespace' =>  'ImiApp\WebSocketServer',
        'type'        =>    Imi\Swoole\Server\Type::WEBSOCKET,
        'host'        =>    '0.0.0.0',
        'port'        =>    9192,
        'mode'      =>  SWOOLE_BASE,
        'configs'   =>    [
            // 'worker_num'        =>  8,
            // 'task_worker_num'   =>  16,
        ],
        'beans' => [
            'ServerUtil' => \Imi\Swoole\Server\Util\LocalServerUtil::class,
            // 'ServerUtil' => \Imi\Swoole\Server\Util\LocalServerUtil::class,
            // 'ServerUtil' => 'RedisServerUtil',
            // 'ServerUtil' => 'SwooleGatewayServerUtil',
        ],
    ]
```  

运行  
```  
vendor/bin/imi-swoole swoole/start
```  
报错
```  
[2022-02-13 20:52:04] imi.ERROR: Uncaught ErrorException: Swoole\Server::start(): use Swoole\Server class and open http related protocols may lead to some errors (inconsistent class type) in /www/wwwroot/iot.tieninc.com/imi/vendor/imiphp/imi-swoole/src/Server/Base.php:136
Stack trace:
#0 [internal function]: Imi\Log\ErrorLog->onError()
#1 /www/wwwroot/iot.tieninc.com/imi/vendor/imiphp/imi-swoole/src/Server/Base.php(136): Swoole\Server->start()
#2 /www/wwwroot/iot.tieninc.com/imi/vendor/imiphp/imi-swoole/src/Server/Cli/Server.php(79): Imi\Swoole\Server\Base->start()
#3 /www/wwwroot/iot.tieninc.com/imi/vendor/imiphp/imi/src/Event/TEvent.php(195): Imi\Swoole\Server\Cli\Server->Imi\Swoole\Server\Cli\{closure}()
#4 /www/wwwroot/iot.tieninc.com/imi/vendor/imiphp/imi/src/Event/Event.php(66): Imi\Event\Event->__trigger()
#5 /www/wwwroot/iot.tieninc.com/imi/vendor/imiphp/imi-swoole/bootstrap.php(96): Imi\Event\Event::trigger()
#6 /www/wwwroot/iot.tieninc.com/imi/vendor/imiphp/imi-swoole/bin/imi-swoole(3): Imi\Swoole\{closure}()
#7 {main}
  thrown 
```

**Comment by sy-records** [comment]
子服务是websocket 主服务要用http
