### ISSUE TITLE
Swoole 4.8 bug

### ISSUE THREAD

**Issue by waghanza** [Yurunsoft/imi#316]
Hi @Yurunsoft,

I have trouble running https://github.com/the-benchmarker/web-frameworks with swoole 

* What problem did you encounter?

I can not start `imi` using `swoole` with `php vendor/bin/imi-swoole swoole/start`

```
Fatal error: Uncaught Swoole\Error: API must be called in the coroutine in @swoole-src/library/core/Coroutine/functions.php:28
Stack trace:
#0 @swoole-src/library/core/Coroutine/functions.php(28): Swoole\Coroutine::defer(Object(Closure))
#1 /usr/src/app/vendor/imiphp/imi-swoole/src/Worker/SwooleWorkerHandler.php(114): Swoole\Coroutine\defer(Object(Closure))
#2 /usr/src/app/vendor/imiphp/imi/src/Worker.php(61): Imi\Swoole\Worker\SwooleWorkerHandler->inited()
#3 /usr/src/app/vendor/imiphp/imi-swoole/src/Server/Base.php(245): Imi\Worker::inited()
#4 [internal function]: Imi\Swoole\Server\Base->Imi\Swoole\Server\{closure}(Object(Swoole\Http\Server), 8)
#5 /usr/src/app/vendor/imiphp/imi-swoole/src/Server/Base.php(146): Swoole\Server->start()
#6 /usr/src/app/vendor/imiphp/imi-swoole/src/Server/Cli/Server.php(79): Imi\Swoole\Server\Base->start()
#7 /usr/src/app/vendor/imiphp/imi/src/Event/TEvent.php(195): Imi\Swoole\Server\Cli\Server->Imi\Swoole\Server\Cli\{closure}(Object(Imi\Event\EventParam))
#8 /usr/src/app/vendor/imiphp/imi/src/Event/Event.php(66): Imi\Event\Event->__trigger('IMI.SWOOLE.MAIN...', Array, NULL, 'Imi\\Event\\Event...')
#9 /usr/src/app/vendor/imiphp/imi-swoole/bootstrap.php(75): Imi\Event\Event::trigger('IMI.SWOOLE.MAIN...')
#10 /usr/src/app/vendor/imiphp/imi-swoole/bin/imi-swoole(3): Imi\Swoole\{closure}()
#11 /usr/src/app/vendor/bin/imi-swoole(117): include('/usr/src/app/ve...')
#12 {main}
  thrown in @swoole-src/library/core/Coroutine/functions.php on line 28
```

* Please execute the following command to get environment information.
> `php -v & php --ri swoole & composer info | grep -a imi`

```
/usr/src/app # php -v && php --ri swoole && composer info | grep -a imi
PHP 8.0.17 (cli) (built: Apr  5 2022 01:58:29) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.17, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.17, Copyright (c), by Zend Technologies

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.8
Built => Apr  7 2022 07:55:24
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
zlib => 1.2.12
brotli => E16777225/D16777225
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
imiphp/imi                         v2.1.7   imi 是一款支持长连接微服务分布式的 PHP 开发框架，它可以运行在 PHP-FPM、Swoole、Workerman、RoadRunner 等多种容器环境...
imiphp/imi-swoole                  v2.1.6   imi swoole component
```

* If you can, Provide the smallest reproducible code:

The whole implentation is in https://github.com/the-benchmarker/web-frameworks/tree/master/php/imi-swoole

**Comment by Yurunsoft** [comment]
Thanks for the feedback, the bug has been fixed, imi will be released tomorrow
