### ISSUE TITLE
mysql事务报错

### ISSUE THREAD

**Issue by mrlovables** [Yurunsoft/imi#398]
* 你遇到了什么问题、建议：

```json
{
    "success": 0,
    "message": "Call to a member function inTransaction() on null",
    "code": 0,
    "file": "/Users/hb/Project/imi-project/vendor/imiphp/imi/src/Db/Drivers/TPdoDriver.php",
    "line": 259,
    "trace": [
        "#0 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Db/Query/Query.php(959): Imi\\Db\\Mysql\\Drivers\\PdoMysql\\Driver->inTransaction()",
        "#1 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Db/Query/Query.php(1061): Imi\\Db\\Query\\Query->isInTransaction()",
        "#2 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Db/Query/Query.php(1324): Imi\\Db\\Query\\Query->buildSelectSql()",
        "#3 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Model/Traits/TModelQuery.php(99): Imi\\Db\\Query\\Query->select()",
        "#4 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Db/Query/Query.php(1370): Imi\\Model\\ModelQuery->select()",
        "#5 /Users/hb/Project/imi-project/Common/Model/HomeworkTask.php(19): Imi\\Db\\Query\\Query->column(Array)",
        "#6 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Facade/BaseFacade.php(90): ImiApp\\Common\\Model\\HomeworkTask->getClsidColumns(Array)",
        "#7 /Users/hb/Project/imi-project/ApiServer/Service/HomeworkTemplateService.php(387): Imi\\Facade\\BaseFacade::__callStatic('getClsidColumns', Array)",
        "#8 /Users/hb/Project/imi-project/ApiServer/Service/HomeworkTemplateService.php(299): ImiApp\\ApiServer\\Service\\HomeworkTemplateService->editHomeworkTask(Object(HomeworkTemplate__Bean__74), Array)",
        "#9 /Users/hb/Project/imi-project/ApiServer/Controller/HomeworkController.php(86): ImiApp\\ApiServer\\Service\\HomeworkTemplateService->edit(Array)",
        "#10 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Util/DelayServerBeanCallable.php(57): ImiApp\\ApiServer\\Controller\\HomeworkController->edit()",
        "#11 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Server/Http/Middleware/ActionMiddleware.php(79): Imi%util\\DelayServerBeanCallable->__invoke()",
        "#12 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Server/Http/Middleware/ActionMiddleware.php(59): Imi\\Server\\Http\\Middleware\\ActionMiddleware->dispatch(Object(Imi\\Swoole\\Http\\Message\\SwooleRequest), Object(Imi\\Swoole\\Http\\Message\\SwooleResponse), Object(Imi\\Server\\Http\\RequestHandler))",
        "#13 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Server/Http/RequestHandler.php(48): Imi\\Server\\Http\\Middleware\\ActionMiddleware->process(Object(Imi\\Swoole\\Http\\Message\\SwooleRequest), Object(Imi\\Server\\Http\\RequestHandler))",
        "#14 /Users/hb/Project/imi-project/ApiServer/Middleware/Auth.php(62): Imi\\Server\\Http\\RequestHandler->handle(Object(Imi\\Swoole\\Http\\Message\\SwooleRequest))",
        "#15 /private/tmp/imi.Wtprzg(25): ImiApp\\ApiServer\\Middleware\\Auth->process(Object(Imi\\Swoole\\Http\\Message\\SwooleRequest), Object(Imi\\Server\\Http\\RequestHandler), Object(Lcobucci\\JWT\\Token\\Plain), Array)",
        "#16 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Bean/BeanProxy.php(242): Auth__Bean__65->{closure}(Object(Imi\\Swoole\\Http\\Message\\SwooleRequest), Object(Imi\\Server\\Http\\RequestHandler), Object(Lcobucci\\JWT\\Token\\Plain), Array)",
        "#17 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Bean/BeanProxy.php(56): Imi\\Bean\\BeanProxy::callOrigin(Object(Auth__Bean__65), 'ImiApp\\\\ApiServe...', 'process', Array, Object(Closure))",
        "#18 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Aop/AroundJoinPoint.php(33): Imi\\Bean\\BeanProxy::Imi\\Bean\\{closure}(Array)",
        "#19 /Users/hb/Project/imi-project/vendor/imiphp/imi-jwt/src/Aop/JWTValidationAop.php(116): Imi\\Aop\\AroundJoinPoint->proceed(Array)",
        "#20 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Util/DelayClassCallable.php(41): Imi\\JWT\\Aop\\JWTValidationAop->around(Object(Imi\\Aop\\AroundJoinPoint))",
        "#21 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Bean/BeanProxy.php(69): Imi%util\\DelayClassCallable->__invoke(Object(Imi\\Aop\\AroundJoinPoint))",
        "#22 /private/tmp/imi.Wtprzg(27): Imi\\Bean\\BeanProxy::call(Object(Auth__Bean__65), 'ImiApp\\\\ApiServe...', 'process', Object(Closure), Array)",
        "#23 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Server/Http/RequestHandler.php(48): Auth__Bean__65->process(Object(Imi\\Swoole\\Http\\Message\\SwooleRequest), Object(Imi\\Server\\Http\\RequestHandler))",
        "#24 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Server/Http/Middleware/ActionWrapMiddleware.php(43): Imi\\Server\\Http\\RequestHandler->handle(Object(Imi\\Swoole\\Http\\Message\\SwooleRequest))",
        "#25 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Server/Http/RequestHandler.php(48): Imi\\Server\\Http\\Middleware\\ActionWrapMiddleware->process(Object(Imi\\Swoole\\Http\\Message\\SwooleRequest), Object(Imi\\Server\\Http\\RequestHandler))",
        "#26 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Server/Http/Middleware/RouteMiddleware.php(42): Imi\\Server\\Http\\RequestHandler->handle(Object(Imi\\Swoole\\Http\\Message\\SwooleRequest))",
        "#27 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Server/Http/RequestHandler.php(48): Imi\\Server\\Http\\Middleware\\RouteMiddleware->process(Object(Imi\\Swoole\\Http\\Message\\SwooleRequest), Object(Imi\\Server\\Http\\RequestHandler))",
        "#28 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Server/Session/Middleware/HttpSessionMiddleware.php(52): Imi\\Server\\Http\\RequestHandler->handle(Object(Imi\\Swoole\\Http\\Message\\SwooleRequest))",
        "#29 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Server/Http/RequestHandler.php(48): Imi\\Server\\Session\\Middleware\\HttpSessionMiddleware->process(Object(Imi\\Swoole\\Http\\Message\\SwooleRequest), Object(Imi\\Server\\Http\\RequestHandler))",
        "#30 /Users/hb/Project/imi-project/ApiServer/Middleware/RequestLog.php(32): Imi\\Server\\Http\\RequestHandler->handle(Object(Imi\\Swoole\\Http\\Message\\SwooleRequest))",
        "#31 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Server/Http/RequestHandler.php(48): ImiApp\\ApiServer\\Middleware\\RequestLog->process(Object(Imi\\Swoole\\Http\\Message\\SwooleRequest), Object(Imi\\Server\\Http\\RequestHandler))",
        "#32 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Server/Http/Middleware/OptionsMiddleware.php(100): Imi\\Server\\Http\\RequestHandler->handle(Object(Imi\\Swoole\\Http\\Message\\SwooleRequest))",
        "#33 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Server/Http/RequestHandler.php(48): Imi\\Server\\Http\\Middleware\\OptionsMiddleware->process(Object(Imi\\Swoole\\Http\\Message\\SwooleRequest), Object(Imi\\Server\\Http\\RequestHandler))",
        "#34 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Server/Http/Dispatcher.php(57): Imi\\Server\\Http\\RequestHandler->handle(Object(Imi\\Swoole\\Http\\Message\\SwooleRequest))",
        "#35 /Users/hb/Project/imi-project/vendor/imiphp/imi-swoole/src/Server/Http/Listener/BeforeRequest.php(49): Imi\\Server\\Http\\Dispatcher->dispatch(Object(Imi\\Swoole\\Http\\Message\\SwooleRequest))",
        "#36 /Users/hb/Project/imi-project/vendor/imiphp/imi/src/Event/TEvent.php(195): Imi\\Swoole\\Server\\Http\\Listener\\BeforeRequest->handle(Object(Imi\\Swoole\\Server\\Event\\Param\\RequestEventParam))",
        "#37 /Users/hb/Project/imi-project/vendor/imiphp/imi-swoole/src/Server/Http/Server.php(128): Imi\\Server\\Contract\\BaseServer->trigger('request', Array, Object(Server__Bean__29), 'Imi\\\\Swoole\\\\Serv...')",
        "#38 [internal function]: Imi\\Swoole\\Server\\Http\\Server->Imi\\Swoole\\Server\\Http\\{closure}(Object(Swoole\\Http\\Request), Object(Swoole\\Http\\Response))",
        "#39 {main}"
    ]
}
```

* 请执行下面的命令获取环境信息。
> `php -v & php --ri swoole & composer info | grep -a imi`

```
PHP 8.1.8 (cli) (built: Jul  8 2022 10:58:31) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.8, Copyright (c) Zend Technologies

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.11
Built => Jul 27 2022 09:11:17
coroutine => enabled with boost asm context
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 1.1.1q  5 Jul 2022
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144

```

* 组件信息

> `composer info|grep -a imiphp`

```
imiphp/imi                         v2.1.20  imi 是一款支持长连接�...
imiphp/imi-grpc                    v2.1.8   在 imi 框架中集成 gRPC ...
imiphp/imi-jwt                     v2.0.10  在 imi 框架中非常方便...
imiphp/imi-rpc                     v2.1.6   在 imi 框架中开发 RPC �...
imiphp/imi-snowflake               v2.0.4   imi 框架的雪花算法生�...
imiphp/imi-swoole                  v2.1.17  imi swoole component
```

* 如果可以，提供最小可复现代码：

```php
// 你的代码

```

**Comment by Yurunsoft** [comment]
在这个错误发生前，有无其他错误日志

另外建议：`Model` 作为 `Facade` 用是不规范的，`HomeworkTask` 代码是否可以贴下？

**Comment by Yurunsoft** [comment]
连接池配置也贴一下，是否设置过什么参数

**Comment by mrlovables** [comment]
没有其他日志

> HomeworkTask

```php
class HomeworkTask extends HomeworkTaskBase
{
    public function getClsidColumns($where): array
    {
        return self::query()->whereEx($where)->column('clsid');
    }

    public function getStudentsColumns($where): string
    {
        return self::query()->whereEx($where)->value('students', '');
    }

    public function getIdColumns($where): array
    {
        return self::query()->whereEx($where)->column('id');
    }
}
```

> 连接池配置

```php
        'maindb' => [
            'pool'     => [
                'class'  => \Imi\Swoole\Db\Pool\CoroutineDbPool::class,
                'config' => [
                    'maxResources' => 10,
                    'minResources' => 0,
                ],
            ],
            'resource' => [
                'host'     => Imi\env('DB_HOST', ''),
                'port'     => Imi\env('DB_PORT', ''),
                'username' => Imi\env('DB_USER', ''),
                'password' => Imi\env('DB_PASS', ''),
                'database' => Imi\env('DB_DATABASE', ''),
                'charset'  => Imi\env('DB_CHARSET', ''),
            ],
        ],
```

**Comment by Yurunsoft** [comment]
看了半天查不出原因，请求前后是否有热更新触发，如果有那就是正常的，生产环境不推荐热更新

**Comment by mrlovables** [comment]
本地环境,有开热更新,应该是热更新导致的连接被释放了

**Comment by Yurunsoft** [comment]
那应该是在释放连接池后，还响应了请求导致的，这个问题不需要特别处理
