### ISSUE TITLE
Timer 中使用 Server::sendToGroup 框架封装方法报错

### ISSUE THREAD

**Issue by azhuang321** [Yurunsoft/imi#422]
### 以下代码都是在 ws的路由方法中
```php
<?php
namespace ImiDemo\WebSocketDemo\MainServer\WSController\Index;
 
use Imi\ConnectionContext;
use Imi\Controller\WebSocketController;
use Imi\Server\WebSocket\Route\Annotation\WSRoute;
use Imi\Server\WebSocket\Route\Annotation\WSAction;
use Imi\Server\WebSocket\Route\Annotation\WSController;
 
/**
 * 数据收发测试
 * @WSController
 */
class Test extends WebSocketController
{
    /**
     * 登录
     *
     * @WSAction
     * @WSRoute({"action"="login"})
     * @return void
     */
    public function login($data)
    {
       Timer::after(1000,function () use (&$test){
            var_dump(Server::sendToGroup('table_1',['test' => 'test']));
       });
        return ['success'=>true];
    }
}
```

* 当 在 ws 的路由中 使用 `Server::sendToGroup` 是正常的 
* 但是在
```php
Timer::after(1000,function () use (&$test){
     var_dump(Server::sendToGroup('table_1',['test' => 'test']));
 });
```
中使用 就会报以下错误:
```php
 Uncaught Error: Call to a member function getProtocol() on null in /www/wwwroot/imi/imi-admin/vendor/imiphp/imi/src/Server/DataParser/DataParser.php:81
Stack trace:
#0 /www/wwwroot/imi/imi-admin/vendor/imiphp/imi/src/Server/DataParser/DataParser.php(27): Imi\Server\DataParser\DataParser->getParserClass()
#1 /www/wwwroot/imi/imi-admin/vendor/imiphp/imi-swoole/src/Server/Util/LocalServerUtil.php(345): Imi\Server\DataParser\DataParser->encode()
#2 /www/wwwroot/imi/imi-admin/vendor/imiphp/imi/src/Server/Server.php(122): Imi\Swoole\Server\Util\LocalServerUtil->sendToGroup()
#3 /www/wwwroot/imi/imi-admin/Front/WsController/Ws/Table.php(87): Imi\Server\Server::sendToGroup()
#4 [internal function]: Bole\Front\WsController\Ws\Table->Bole\Front\WsController\Ws\{closure}()
#5 {main}
  thrown  
```

但是 如果我不使用框架封装的方法 直接使用 swoole 原生的`push`方法是可以推送消息的
以下是正常代码
```php
 $server = Server::getServer(null,ISwooleServer::class)->getSwooleServer();
      Timer::tick(10000,function () use(&$server){
          foreach ($server->connection_list() as $v) {
              if ($server->isEstablished($v)) {
                  $server->push($v,'');
              }
          }
});
```
但是我是用原生的方法推,肯定就不会自动的 `encode/decode`  ws的消息了 

* 请执行下面的命令获取环境信息。
> `php -v & php --ri swoole & composer info | grep -a imi`

```
[root@4b9d30e2ae5a imi-admin]# php81 -v & php81 --ri swoole & composer info | grep -a imi
[1] 98716
[2] 98717
PHP 8.1.9 (cli) (built: Aug 13 2022 21:51:59) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.11
Built => Aug 13 2022 21:58:19
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => 1.2.7
brotli => E16777223/D16777223
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
imiphp/imi                         v2.1.25  imi 是一款支持长连接微服务分布�...
imiphp/imi-jwt                     v2.1.7   在 imi 框架中非常方便地接入 jwt
imiphp/imi-queue                   v2.1.13  imi 框架的队列组件，使用 Redis 作�...
imiphp/imi-swoole                  v2.1.22  imi swoole component
phpben/imi-auth                    v1.1.7   基于IMI的AUTH组件。
phpben/imi-config-center           v1.0.4   基于IMI的配置中心。
phpben/imi-module-route            v1.0.1   基于IMI的模块化路由。
phpben/imi-validate                v1.1.1   基于IMI的Validation组件。
[1]-  Done                    php81 -v
[2]+  Done                    php81 --ri swoole
[root@4b9d30e2ae5a imi-admin]# 
```

**Comment by Yurunsoft** [comment]
`Server::sendToGroup()` 需要传服务器名，因为在 Timer 回调里已经没有当前服务器上下文了
