### ISSUE TITLE
定时任务，偶然会报Wrong parameters for RuntimeException错误

### ISSUE THREAD

**Issue by mp5a6mg** [Yurunsoft/imi#429]
* 你遇到了什么问题、建议：
执行定时任务时，偶然会报Wrong parameters for RuntimeException错误

* 请执行下面的命令获取环境信息。
> `php -v & php --ri swoole & composer info | grep -a imi`

```
# 粘贴到这里
PHP 7.4.30 (cli) (built: Jun 27 2022 12:13:39) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.5
Built => Jun  9 2022 20:06:41
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.0.2u  20 Dec 2019
pcre => enabled
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled
```

* 如果可以，提供最小可复现代码：

```php
// 你的代码


imi.ERROR: Error: Wrong parameters for RuntimeException([string $message [, long $code [, Throwable $previous = NULL]]]) in /var/www/wmzp_backend_im/vendor/imiphp/imi/src/Cron/CronWorker.php:57
Stack trace:
#0 /var/www/wmzp_backend_im/vendor/imiphp/imi/src/Cron/CronWorker.php(57): Exception->__construct('Task CornVirtua...', '23000', Object(PDOException))
#1 /var/www/wmzp_backend_im/vendor/imiphp/imi-swoole/src/Cron/Listener/WorkerPartPipeMessage.php(44): Imi\Cron\CronWorker->exec('CornVirtualJob', NULL, 'ImiApp\\WebSocke...', 'random_worker')
#2 /var/www/wmzp_backend_im/vendor/imiphp/imi/src/Event/TEvent.php(53): Imi\Swoole\Cron\Listener\WorkerPartPipeMessage->handle(Object(Imi\Event\EventParam))
#3 /var/www/wmzp_backend_im/vendor/imiphp/imi/src/Event/TEvent.php(195): Imi\Event\Event::Imi\Event\{closure}(Object(Imi\Event\EventParam))
#4 /var/www/wmzp_backend_im/vendor/imiphp/imi/src/Event/Event.php(66): Imi\Event\Event->__trigger('IMI.PIPE_MESSAG...', Array, NULL, 'Imi\\Event\\Event...')
#5 /var/www/wmzp_backend_im/vendor/imiphp/imi-swoole/src/Server/Listener/OnPipeMessage.php(30): Imi\Event\Event::trigger('IMI.PIPE_MESSAG...', Array)
#6 /var/www/wmzp_backend_im/vendor/imiphp/imi/src/Event/TEvent.php(53): Imi\Swoole\Server\Listener\OnPipeMessage->handle(Object(Imi\Swoole\Server\Event\Param\PipeMessageEventParam))
#7 /var/www/wmzp_backend_im/vendor/imiphp/imi/src/Event/TEvent.php(195): Imi\Event\Event::Imi\Event\{closure}(Object(Imi\Swoole\Server\Event\Param\PipeMessageEventParam))
#8 /var/www/wmzp_backend_im/vendor/imiphp/imi/src/Event/Event.php(66): Imi\Event\Event->__trigger('IMI.MAIN_SERVER...', Array, Object(Server__Bean__30), 'Imi\\Swoole\\Serv...')
#9 /var/www/wmzp_backend_im/vendor/imiphp/imi-swoole/src/Server/Base.php(378): Imi\Event\Event::trigger('IMI.MAIN_SERVER...', Array, Object(Server__Bean__30), 'Imi\\Swoole\\Serv...')
#10 {main}  
```

**Comment by Yurunsoft** [comment]
是 php 底层问题，已反馈：https://github.com/php/php-src/issues/9529

稍后会在 imi 做兼容处理。
