### ISSUE TITLE
vendor/bin/imi-swoole swoole/stop 停止 进程未停止完

### ISSUE THREAD

**Issue by azhuang321** [Yurunsoft/imi#453]
* 你遇到了什么问题、建议：
使用 `vendor/bin/imi-swoole swoole/stop` 停止 进程未完全停止完,主要是 框架会报以下错误
```shell
[2022-10-31 12:37:30] imi.ERROR: RedisException: read error on connection to 127.0.0.1:51000 in /www/imi-admin/vendor/imiphp/imi/src/Redis/RedisHandler.php:297
Stack trace:
#0 /www/imi-admin/vendor/imiphp/imi/src/Redis/RedisHandler.php(297): Redis->subscribe()
#1 /www/imi-admin/vendor/imiphp/imi-swoole/src/Server/Util/RedisServerUtil.php(321): Imi\Redis\RedisHandler->__call()
#2 /www/imi-admin/vendor/imiphp/imi/src/functions.php(57): Imi\Swoole\Server\Util\RedisServerUtil->Imi\Swoole\Server\Util\{closure}()
#3 /www/imi-admin/vendor/imiphp/imi-swoole/src/functions.php(22): {closure}()
#4 [internal function]: {closure}()
#5 {main} 
```
出现了 报错 **就导致进程未停止完 成了僵尸进程了**

* 请执行下面的命令获取环境信息。
> `php -v & php --ri swoole & composer info | grep -a imi`

```
PHP 8.1.9 (cli) (built: Aug 13 2022 21:51:59) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.9, Copyright (c) Zend Technologies

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.8.11
Built => Aug 13 2022 21:58:19
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
openssl => OpenSSL 1.0.2k-fips  26 Jan 2017
http2 => enabled
pcre => enabled
zlib => 1.2.7
brotli => E16777223/D16777223
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
imiphp/imi                         v2.1.26  imi 是款支持长连接�...
imiphp/imi-jwt                     v2.1.7   在 imi 框架中非常方便...
imiphp/imi-queue                   v2.1.13  imi 框的队列组件，�...
imiphp/imi-swoole                  v2.1.23  imi swoole component
phpben/imi-config-center           v1.0.4   基于IM配置中心。
phpben/imi-validate                v1.1.1   基于IMValidation组件。
[1]-  Done                    php81 -v
[2]+  Done                    php81 --ri swoole

```

**Comment by azhuang321** [comment]
文档中: 有这么一句 `resource.options 中加入：\Redis::OPT_READ_TIMEOUT => -1，防止 read error on connection to xxx 错误刷屏`
但是我已经加过了 但是还是会出问题

**Comment by azhuang321** [comment]
![image](https://user-images.githubusercontent.com/63149232/198996567-ddc8b219-bb1d-479c-862e-e9dee72d35cd.png)
我发现是queue 的 进程没有被杀掉

**Comment by Yurunsoft** [comment]
无法复现

**Comment by Yurunsoft** [comment]
报错不是导致僵尸进程的原因，报错是正常的。

检查一下消费者里是否有死循环、阻塞，建议提供个最小可复现项目代码。

**Comment by azhuang321** [comment]
> 报错不是导致僵尸进程的原因，报错是正常的。
> 
> 检查一下消费者里是否有死循环、阻塞，建议提供个最小可复现项目代码。

确实报错不是 导致僵尸进程的原因,我是重新创建一个代码 使用队列 然后停止确实也没问题

**Comment by azhuang321** [comment]
我发现 我的代码停止的时候是杀掉了queue的主进程 子进程没有随着主进程消失,哎 我得检查一下

**Comment by azhuang321** [comment]
我即使把消费者里 只留下
```php
protected function consume(IMessage $message, IQueueDriver $queue): void{

    }
```
依旧还是有问题

**Comment by Yurunsoft** [comment]
你是用的imi-admin？有没有可能里面有没有结束的死循环？

**Comment by azhuang321** [comment]
对哈  我新建的代码是用的 官方的demo 我再去试一下

**Comment by azhuang321** [comment]
看样子 应该是有阻塞 导致的

**Comment by azhuang321** [comment]
也是 没有问题  还是我代码有问题 我看看把

**Comment by azhuang321** [comment]
没找到 自己写了命令 再去停止 发送退出信号就可以了
