### ISSUE TITLE
websocket服务器推送指定客户端ID消息失败

### ISSUE THREAD

**Issue by luobutouzi** [Yurunsoft/imi#582]
* 问题
客户端AB 同时连接到websocket服务器。
客户端A发出指令到服务器，服务器把客户端A的指令转发到客户端B。客户端B收到消息执行完数据返回给服务器，服务器在推送给客户端A。

如果执行 rm -rf .runtime并重新启动websocket服务器，两个客户端重新连接 消息正常接收和推送。
但是比如服务器停止（客户端B断线重连；两者都会导致错误），客户端B重新连接后，就报错：
![图片](https://github.com/imiphp/imi/assets/41530685/f56f7a1d-202e-4477-9d9c-d9bcfda3a320)

报错之后：
客户端AB 发送给服务器消息后，都能收到“服务器”直接返回的消息，但是无法推送“指定fd消息”给客户端B。

* 应用配置config/config.php
![图片](https://github.com/imiphp/imi/assets/41530685/635299b3-a6fd-442b-b59a-c7e7972007be)

* 全局 config/config.php
![图片](https://github.com/imiphp/imi/assets/41530685/d8728ce9-5f1f-4f87-a583-489dfe663407)

* 错误日志

```
[2023-08-31 15:07:58] imi.ERROR: ErrorException: Swoole\WebSocket\Server::push(): session#3 does not exists in /home/wwwroot/ping/vendor/imiphp/imi-swoole/src/Server/WebSocket/Server.php:354
Stack trace:
#0 [internal function]: Imi\Log\ErrorLog->onError()
#1 /home/wwwroot/ping/vendor/imiphp/imi-swoole/src/Server/WebSocket/Server.php(354): Swoole\WebSocket\Server->push()
#2 /home/wwwroot/ping/app/websocket/controller/ping/ClientController.php(62): Imi\Swoole\Server\WebSocket\Server->push()
#3 /home/wwwroot/ping/vendor/imiphp/imi/src/Util/DelayServerBeanCallable.php(86): ImiApp\app\websocket\controller\ping\ClientController->singlePing()
#4 /home/wwwroot/ping/vendor/imiphp/imi/src/Server/WebSocket/Middleware/ActionMiddleware.php(40): Imi\Util\DelayServerBeanCallable->__invoke()
#5 /home/wwwroot/ping/vendor/imiphp/imi/src/Server/WebSocket/Middleware/ActionWrapMiddleware.php(47): Imi\Server\WebSocket\Middleware\ActionMiddleware->process()
#6 /home/wwwroot/ping/vendor/imiphp/imi/src/Server/WebSocket/MessageHandler.php(53): Imi\Server\WebSocket\Middleware\ActionWrapMiddleware->process()
#7 /home/wwwroot/ping/vendor/imiphp/imi/src/Server/WebSocket/Middleware/RouteMiddleware.php(45): Imi\Server\WebSocket\MessageHandler->handle()
#8 /home/wwwroot/ping/vendor/imiphp/imi/src/Server/WebSocket/MessageHandler.php(53): Imi\Server\WebSocket\Middleware\RouteMiddleware->process()
#9 /home/wwwroot/ping/vendor/imiphp/imi/src/Server/WebSocket/Dispatcher.php(33): Imi\Server\WebSocket\MessageHandler->handle()
#10 /home/wwwroot/ping/vendor/imiphp/imi-swoole/src/Server/WebSocket/Listener/BeforeMessage.php(41): Imi\Server\WebSocket\Dispatcher->dispatch()
#11 /home/wwwroot/ping/vendor/imiphp/imi/src/Event/TEvent.php(53): Imi\Swoole\Server\WebSocket\Listener\BeforeMessage->handle()
#12 /home/wwwroot/ping/vendor/imiphp/imi/src/Event/TEvent.php(202): Imi\Server\Contract\BaseServer::Imi\Event\{closure}()
#13 /home/wwwroot/ping/vendor/imiphp/imi-swoole/src/Server/WebSocket/Server.php(203): Imi\Server\Contract\BaseServer->trigger()
#14 [internal function]: Imi\Swoole\Server\WebSocket\Server->Imi\Swoole\Server\WebSocket\{closure}()
#15 {main}

```

* 环境信息。
```
PHP 8.1.22 (cli) (built: Aug 26 2023 01:37:10) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.22, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.22, Copyright (c), by Zend Technologies

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.0.2
Built => Aug 26 2023 01:41:37
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1n  15 Mar 2022
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
c-ares => 1.17.1
zlib => 1.2.11
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
mysqlnd => enabled
async_redis => enabled
coroutine_postgresql => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? 
imiphp/imi                         v2.1.52  imi 是一款支持长连接微服务分布式的 PHP 开发框架，可在 PHP-FPM、Swoole、Workerman 和 RoadRunner 等多种容器环境下运行。它支持 HttpApi、WebSoc...
imiphp/imi-swoole                  v2.1.41  imi swoole component
phpben/imi-validate                v1.1.1   基于IMI的Validation组件。
[1]-  Done                    php -v
[2]+  Done                    php --ri swoole
```

**Comment by Yurunsoft** [comment]
每次连接后fd是不一样的

还需要看下你的发送代码

**Comment by Yurunsoft** [comment]
`SWOOLE_BASE` 模式下，WebSocket 的 `push()` 不支持跨进程推送，imi底层做了支持，所以用服务器工具类发送就可以解决

<https://doc.imiphp.com/v2.1/utils/Server.html#send>
